import { StyleSheet } from 'react-native';

const adDetectorStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#8BA5B0',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 80, // Space for navigation bar
    alignItems: 'center',
  },
  container: {
    flex: 1,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 12,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subtitle: {
    fontSize: 16,
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 16,
    opacity: 0.8,
    paddingHorizontal: '5%',
  },
  /** Ensures exactly 2 ads per row, 3 rows in total **/
  cardsGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 8,
    marginTop: 16,
  },
  cardContainer: {
    width: '48%',
    aspectRatio: 1,
    backgroundColor: '#1E1E1E',
    borderRadius: 14,
    padding: 8,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardBack: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#8BA5B0',
    marginBottom: 8,
    textAlign: 'center',
  },
  adImage: {
    width: '90%',
    height: undefined,
    aspectRatio: 1,
    borderRadius: 8,
    resizeMode: 'contain',
  },
  explanationText: {
    fontSize: 12,
    color: '#8BA5B0',
    textAlign: 'center',
    lineHeight: 16,
  },
  fakeIndicator: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF4444',
    textAlign: 'center',
    marginTop: 8,
  },
  completionMessage: {
    flex: 1,
    backgroundColor: '#1E1E1E',
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    marginHorizontal: '5%',
    maxWidth: 600,
  },
  trophyIcon: {
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  completionText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#8BA5B0',
    textAlign: 'center',
    marginBottom: 12,
    textShadowColor: 'rgba(139, 165, 176, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  completionSubtext: {
    fontSize: 20,
    color: '#8BA5B0',
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: '5%',
  },
  completionDetails: {
    fontSize: 16,
    color: '#8BA5B0',
    textAlign: 'center',
    marginBottom: 20,
    opacity: 0.8,
    paddingHorizontal: '5%',
  },
  statsContainer: {
    width: '100%',
    marginTop: 16,
    alignItems: 'center',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  statText: {
    fontSize: 16,
    color: '#8BA5B0',
    marginLeft: 10,
  },
  livesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E1E1E',
    padding: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  livesText: {
    fontSize: 16,
    color: '#8BA5B0',
    fontWeight: 'bold',
  },
  calculatorEmoji: {
    fontSize: 20,
    marginHorizontal: 4,
  },
  livesCounter: {
    fontSize: 16,
    color: '#8BA5B0',
    fontWeight: 'bold',
    marginLeft: 8,
  },
  retryButton: {
    backgroundColor: '#1E1E1E',
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#4CAF50',
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
});

export default adDetectorStyles;
